# Generated by Django 2.2.4 on 2019-09-23 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MesasConta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesa', models.IntegerField(default=0, verbose_name='mesa')),
                ('conta', models.IntegerField(default=0, verbose_name='conta')),
                ('total', models.FloatField(default=0.0, verbose_name='Total')),
                ('dinheiro', models.FloatField(default=0.0, verbose_name='Dinheiro')),
                ('cartao_credito', models.FloatField(default=0.0, verbose_name='Cartão credito')),
                ('cartao_debito', models.FloatField(default=0.0, verbose_name='Cartão debito')),
                ('outros', models.FloatField(default=0.0, verbose_name='Outros')),
            ],
        ),
        migrations.CreateModel(
            name='ItensMesaContaMongo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_g6', models.CharField(max_length=24, verbose_name='ID do produto')),
                ('produto', models.CharField(max_length=100, verbose_name='Nome do produto')),
                ('cancelado', models.BooleanField(default=False)),
                ('id_garcom', models.CharField(blank=True, max_length=24, verbose_name='ID do Garcom')),
                ('garcom_nome', models.CharField(blank=True, max_length=100, verbose_name='Garcom')),
                ('percent_comissao', models.FloatField(blank=True, default=0.0, verbose_name='Percentual da comissao')),
                ('comissao', models.FloatField(default=0.0, verbose_name='Comissao')),
                ('unidade_medida', models.CharField(max_length=10, verbose_name='Unidade de medida')),
                ('quantidade', models.FloatField(default=0.0, verbose_name='Quantidade')),
                ('unitario', models.FloatField(default=0.0, verbose_name='Unitario')),
                ('total', models.FloatField(default=0.0, verbose_name='Total')),
                ('mesa_conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='Restaurante.MesasConta')),
            ],
            options={
                'default_permissions': ('index', 'mesa_conta', 'get_add_item_mesa', 'set_add_item_mesa', 'fechar_conta'),
            },
        ),
    ]
