# Generated by Django 2.2.4 on 2019-11-12 14:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurante', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesasconta',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mesasconta',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
