# Generated by Django 3.0.1 on 2019-12-26 15:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurante', '0002_auto_20191112_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='itensmesacontamongo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itensmesacontamongo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
