# Generated by Django 3.0.1 on 2019-12-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurante', '0003_auto_20191226_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesasconta',
            name='troco',
            field=models.FloatField(default=0.0, verbose_name='Troco'),
        ),
    ]
