# Generated by Django 3.0.1 on 2019-12-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='McmmForNextMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=100, verbose_name='Razão Social')),
                ('registro_anp', models.CharField(max_length=40, verbose_name='Registro ANP')),
                ('tipo_instacao', models.SmallIntegerField(verbose_name='Tipo de Instalação')),
                ('capacidade_kg', models.FloatField(verbose_name='Capacidade de Armazenamento em KG')),
                ('distribuidora', models.CharField(max_length=100, verbose_name='Distribuidora')),
                ('longradouro', models.CharField(max_length=100, verbose_name='Longradouro')),
                ('numero', models.IntegerField(verbose_name='Numero')),
                ('bairro', models.CharField(max_length=50, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado')),
                ('cnpj', models.CharField(max_length=14, verbose_name='Estado')),
            ],
        ),
    ]
