# Generated by Django 2.2.4 on 2019-09-20 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contratos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField()),
                ('id_g6', models.CharField(max_length=24, verbose_name='id da movimentacao')),
                ('id_g6_cliente', models.CharField(max_length=24, verbose_name='id do cliente')),
                ('excluido', models.BooleanField()),
                ('motivo', models.CharField(max_length=250, verbose_name='Motivo do cancelamento')),
                ('desconto', models.FloatField(default=0.0, verbose_name='Desconto')),
            ],
        ),
        migrations.CreateModel(
            name='Parcelas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_g6', models.CharField(max_length=24, verbose_name='id da parcela')),
                ('valor', models.FloatField(verbose_name='Valor Parcela')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='Financeiro.Contratos')),
            ],
        ),
    ]
