# Generated by Django 3.0.7 on 2020-06-09 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratos',
            name='bson_data',
            field=models.TextField(null=True, verbose_name='Dados para re-inserir'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='bson_renegociadas',
            field=models.TextField(null=True, verbose_name='Dados para re-inserir'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='data_alteracao',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contratos',
            name='usuario',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='contratos_user', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
            preserve_default=False,
        ),
    ]
