# Generated by Django 2.1.3 on 2018-11-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratos',
            name='desconto',
            field=models.FloatField(default=0.0, verbose_name='Desconto'),
        ),
    ]
