# Generated by Django 2.1.1 on 2018-10-22 19:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Financeiro', '0002_contratos_id_g6'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratos',
            name='id_g6_cliente',
            field=models.CharField(default=django.utils.timezone.now, max_length=24, verbose_name='id do cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contratos',
            name='motivo',
            field=models.CharField(default=django.utils.timezone.now, max_length=250, verbose_name='Motivo do cancelamento'),
            preserve_default=False,
        ),
    ]
