# Generated by Django 3.0.1 on 2020-06-15 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Financeiro', '0002_auto_20200609_1118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contratos',
            options={'default_permissions': ('gerar_financeiro', 'comprovante_debito', 'listagem_contratos', 'parcelas_cliente', 'renegociacao', 'gerador_cartas', 'cancelar_contrato', 'anular_cancelamento_contrato')},
        ),
    ]
