# Generated by Django 2.1.1 on 2018-10-29 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Financeiro', '0003_auto_20181022_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcelas',
            old_name='orcamento',
            new_name='contrato',
        ),
    ]
